### ISSUE TITLE
Can corpy detokenize a tokenized sentence?

### ISSUE THREAD

**Issue by TingxunShi** [dlukes/corpy#1]
Seems the library doesn't provide such a function so I just want to confirm. If it cannot, would you plan to support this? Thank you

**Comment by dlukes** [comment]
Sorry for not replying earlier; I had no idea one has to [enable Watch on one's own repositories](https://github.community/t5/How-to-use-Git-and-GitHub/Get-email-notifications-for-new-pr-s-and-new-issues-on-my-github/td-p/22187) in order to get notified about new issues, so I wasn't aware of your question until I went to the repo today to add an issue myself :)

Could you be more specific, please? `corpy` currently offers interfaces to two tokenizers/taggers, MorphoDiTa and UDPipe. Which one are you interested in?

**Comment by dlukes** [comment]
And maybe provide an example so that I have a better idea of what you're trying to do :)

**Comment by dlukes** [comment]
No feedback for over a year, so closing, but feel free to reopen if it's still a pain point! :)
